### ISSUE TITLE
My Resume Draft

### ISSUE THREAD

**Issue by DiwthL83** [DiwthL83/20160816-Assignment#1]

**Comment by sumeetjain** [comment]
Thanks Jerry. It's going to be hard to provide feedback on this, because it's not a Google Doc. The document you're using might look different on my computer than it does on yours. Please re-submit, using the Google Doc. Otherwise, looking good (But I'll be glad to see the assignment completed tomorrow).

**Comment by DiwthL83** [comment]
Sorry about that, I'll submit the final draft via Google Docs.
